CREATE TABLE IF NOT EXISTS PERSON (
    ID INTEGER IDENTITY PRIMARY KEY,
    FIRST_NAME varchar(255),
    LAST_NAME varchar(255),
    DATE_OF_BIRTH DATETIME,
    PROFFESSION varchar(255)
);

CREATE TABLE IF NOT EXISTS ALBUM(
    ID INTEGER IDENTITY PRIMARY KEY,
    TITLE varchar(255),
);

CREATE TABLE IF NOT EXISTS SONG(
    ID INTEGER IDENTITY PRIMARY KEY,
    TITLE varchar(255),
    DURATION_IN_SEC INTEGER,
    ALBUM INTEGER REFERENCES ALBUM,
    ALBUM_KEY INTEGER
);
